parameters:
    wise_web_cms_connector.version: 1

services:
    wiseweb_cms_connector.connector:
        class: WiseWeb\CmsConnectorBundle\Connector\CmsConnector
        arguments:
            - '@wiseweb_cms_connector.factory.response_status_factory'
            - '@wiseweb_cms_connector.factory.request_factory'
        tags:
            - { name: wiseweb.posting.connector }

    wiseweb_cms_connector.factory.response_status_factory:
        class: WiseWeb\CmsConnectorBundle\Connector\Factory\ResponseStatusFactory

    wiseweb_cms_connector.factory.request_factory:
        class: WiseWeb\CmsConnectorBundle\Connector\Factory\RequestFactory

    # Status code response status factories.

    wiseweb_cms_connector.factory.response_status_factory.created_factory:
        class: WiseWeb\CmsConnectorBundle\Connector\Factory\ResponseStatusFactory\CreatedResponseStatusFactory
        tags:
            - { name: wiseweb_cms_connector.status_code_factory }

    wiseweb_cms_connector.factory.response_status_factory.updated_factory:
        class: WiseWeb\CmsConnectorBundle\Connector\Factory\ResponseStatusFactory\UpdatedResponseStatusFactory
        tags:
            - { name: wiseweb_cms_connector.status_code_factory }

    wiseweb_cms_connector.factory.response_status_factory.deleted_factory:
        class: WiseWeb\CmsConnectorBundle\Connector\Factory\ResponseStatusFactory\DeletedResponseStatusFactory
        tags:
            - { name: wiseweb_cms_connector.status_code_factory }
